<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Payment Receipt</title>
  <style>
    body { font-family: Arial, sans-serif; font-size: 14px; }
    .header { text-align: center; margin-bottom: 20px; }
    .details { margin-bottom: 15px; }
    .footer { margin-top: 30px; font-size: 12px; text-align: center; }
    table { width: 100%; border-collapse: collapse; }
    td, th { padding: 8px; border: 1px solid #ddd; }
  </style>
</head>
<body>
  <div class="header">
    <h2>MediCare Clinic</h2>
    <h4>Payment Receipt</h4>
  </div>

  <div class="details">
    <p><strong>Reference Number:</strong> {{ $payment->reference_number }}</p>
    <p><strong>Patient:</strong> {{ $payment->user->firstname }} {{ $payment->user->lastname }}</p>
    <p><strong>Doctor:</strong> Dr. {{ $payment->appointment->doctor->firstname }} {{ $payment->appointment->doctor->lastname }}</p>
    <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($payment->transaction_date)->format('M d, Y h:i A') }}</p>
  </div>

  <table>
    <tr>
      <th>Payment Method</th>
      <th>Amount</th>
      <th>Status</th>
    </tr>
    <tr>
      <td>{{ ucfirst($payment->payment_method) }}</td>
      <td>PHP {{ number_format($payment->amount, 2) }}</td>
      <td>{{ ucfirst($payment->payment_status) }}</td>
    </tr>
  </table>

  <div class="footer">
    <p>Thank you for your payment! This is an official receipt generated by MediCare System.</p>
  </div>
</body>
</html>
